<a href="https://colab.research.google.com/github/BiancadeFrancisco/RedeNeural_BankPersonalLoan/blob/main/Redes_Neurais_na_Pr%C3%A1tica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/Bank_Personal_Loan_Modelling.xlsx")

df.head()

,ID,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard
0,1,25,1,49,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,4,1.0,2,0,0,0,0,0,1

In [ ]:
# NESSE CASO A COLUNA ID NÃO É NECESSÁRIA, PODEMOS EXCLUI-LA:

df.drop(columns=["ID"])

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0
4996,30,4,15,4,0.4,1,85,0,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,0,1,0
4999,28,4,83,3,0.8,1,0,0,0,0,1,1

In [ ]:
df.describe()

,ID,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal_Loan,Securities_Account,CD_Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,2.396400,1.937913,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,1.147663,1.747666,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [ ]:
# VERIFICAR A DISTRIBUIÇÃO DA NOSSA VARIÁVEL TARGET:

df["Personal_Loan"].value_counts() # resultado: não 4520, sim 480

0    4520
1     480
Name: Personal_Loan, dtype: int64

In [ ]:
# SEPARAR AS VARIÁVEIS:

x = df.drop(columns=["Personal_Loan"])  # todas, menos a coluna Personal_Loan (target)

y = df["Personal_Loan"]

In [ ]:
# SEPARAR TREINO E TESTE:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test, = train_test_split(x, y, test_size=0.2)

In [ ]:
# FAZER NORMALIZAÇÃO DAS NOSSAS VARIÁVEIS:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [ ]:
# TRANSFORMAR TUDO EM DATAFRAME:

X_train = pd.DataFrame(X_train_scaled, columns = X_train.columns)

X_test = pd.DataFrame(X_test_scaled, columns = X_test.columns)

In [ ]:
# IMPLEMENTAR A REDE NEURAL:

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

clf = MLPClassifier(hidden_layer_sizes = (100, 50, 20), activation = "logistic")
# hiperparâmetro (camadas escondidas = "hidden_layer_sizes = (100, 50, 20)") e a função de ativação (sigmoide = "activation = "logistic")

clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

MLPClassifier(activation='logistic', hidden_layer_sizes=(100, 50, 20))

In [ ]:
# VERIFICAR A ACURÁCIA E O F1 DO MODELO:

y_pred = clf.predict(X_test)
print(f"Acurácia: {accuracy_score(y_test, y_pred)*100}%")
print(f"F1 Score: {f1_score(y_test, y_pred)*100}%")

Acurácia: 97.3%
F1 Score: 86.4321608040201%

In [ ]:
# COM OS RESULTADOS, PODEMOS DIZER QUE É UM MODELO BOM PARA SE UTILIZAR.